import { GitAgent } from './git.js';
import { GitHubAgent } from './github.js';
import { logger } from '../logger.js';
import crypto from 'crypto';

export interface SelfHealingOptions {
  repoOwner: string;
  repoName: string;
  baseBranch: string;
  prTitle?: string;
  prBody?: string;
}

export class SelfHealingAgent {
  private git: GitAgent;
  private github: GitHubAgent;

  constructor(workspaceRoot: string = process.cwd()) {
    this.git = new GitAgent(workspaceRoot);
    this.github = new GitHubAgent();
  }

  /**
   * Commits the current workspace changes, pushes them to a new branch, 
   * and opens a PR against the base branch.
   */
  async submitFix(options: SelfHealingOptions): Promise<string | null> {
    const hasChanges = await this.git.hasChanges();
    if (!hasChanges) {
      logger.info('No changes detected in workspace. Skipping Self-Healing PR.');
      return null;
    }

    // Generate a unique branch name
    const shortHash = crypto.randomBytes(3).toString('hex');
    const fixBranch = `dat-autofix-${shortHash}`;

    logger.info(`Initiating Self-Healing PR workflow on branch: ${fixBranch}`);

    // 1. Branch
    const branched = await this.git.createBranch(fixBranch);
    if (!branched) return null;

    // 2. Commit
    const commitMessage = options.prTitle || 'Fix: Autonomous Remediation applied by DAT';
    const committed = await this.git.commitChanges(commitMessage);
    if (!committed) return null;

    // 3. Push
    const pushed = await this.git.pushBranch(fixBranch);
    if (!pushed) return null;

    // 4. Open PR
    const prBody = options.prBody || 'This PR was automatically generated by the Deployment Assist Tool (DAT) Autonomous Remediation Engine.';
    
    const prUrl = await this.github.createPullRequest({
      owner: options.repoOwner,
      repo: options.repoName,
      head: fixBranch,
      base: options.baseBranch,
      title: commitMessage,
      body: prBody
    });

    // 5. Checkout back to original branch (optional cleanup)
    // await this.git.createBranch(options.baseBranch); 

    return prUrl;
  }
}
